[package]
name = "ibmatch"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
hnsw_rs = "0.3.2"
rocksdb = "0.24.0"
once_cell = "1.21.3"
rand = "0.9.2"
dashmap = "6.1.0"

[dev-dependencies]
tempdir = "0.3.7"